[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "divide"
authors = [{name = "Sachin Singh", email = "sachinsingh3198@gmail.com"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/sachinsingh3107/firstmodule"